package com.antgskds.calendarassistant.core.query

import com.antgskds.calendarassistant.data.model.MySettings

interface SettingsTransformApi {
    fun applyPreferenceUpdate(
        current: MySettings,
        showTomorrow: Boolean? = null,
        dailySummary: Boolean? = null,
        dailySummaryMorningMinuteOfDay: Int? = null,
        dailySummaryEveningMinuteOfDay: Int? = null,
        liveCapsule: Boolean? = null,
        pickupAggregation: Boolean? = null,
        hapticFeedbackEnabled: Boolean? = null,
        edgeBarEnabled: Boolean? = null,
        floatingWindow: Boolean? = null,
        advanceReminderEnabled: Boolean? = null,
        advanceReminderMinutes: Int? = null,
        autoArchive: Boolean? = null,
        recognitionMode: Int? = null,
        defaultEventDurationMinutes: Int? = null,
        useMultimodalAi: Boolean? = null,
        disableThinking: Boolean? = null,
        localSemanticEnabled: Boolean? = null,
        selectedLocalModelId: String? = null,
        floatingEventRange: Int? = null,
        floatingExpandSide: String? = null,
        quickMemoRecordingDisplayMode: Int? = null,
        floatingEntryStyle: Int? = null,
        floatingBallEnabled: Boolean? = null,
        floatingBallXPercent: Float? = null,
        floatingBallYPercent: Float? = null,
        floatingBallSizeDp: Int? = null,
        floatingBallAlpha: Float? = null,
        floatingBallSingleTapAction: Int? = null,
        floatingBallDoubleTapAction: Int? = null,
        floatingBallLongPressAction: Int? = null,
        edgeBarSingleTapAction: Int? = null,
        edgeBarDoubleTapAction: Int? = null,
        edgeBarLongPressAction: Int? = null,
        volumeUpLongPressEnabled: Boolean? = null,
        volumeUpLongPressAction: Int? = null,
        smsMonitoring: Boolean? = null,
        forceInstantCodeTimeToNow: Boolean? = null,
        predictiveBackEnabled: Boolean? = null,
        clipboardCodeRecognitionEnabled: Boolean? = null,
        voiceInputEnabled: Boolean? = null,
        floatingVoiceLongPressEnabled: Boolean? = null,
        floatingTextQuickMemoAutoPinEnabled: Boolean? = null,
        voiceQuickMemoAutoPinEnabled: Boolean? = null,
        widgetThemeMode: Int? = null,
        widgetBackgroundAlpha: Float? = null,
        developerOptionsUnlocked: Boolean? = null,
        developerOptionsEnabled: Boolean? = null,
        developerOptionsDisabledAtMillis: Long? = null,
        homeBottomItems: List<String>? = null,
        homeStartPageKey: String? = null,
        liveNotificationTemplateMode: String? = null,
    ): MySettings
}
